/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentationTier;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JSpinner;

/**
 *
 * @author 113453272
 */
public class frmCashUp extends javax.swing.JFrame {
    private static String dbURL = "jdbc:derby:DATABASE;create=true;user=test;password=test";
    private static Connection conn = null;
    private static Statement stmt = null;
    String tempString;
    double tempDouble;
    double salesToday =0;
    /**
     * Creates new form frmCashUpp
     */
    public frmCashUp() {
        initComponents();
        setUp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lab7 = new javax.swing.JLabel();
        lab6 = new javax.swing.JLabel();
        lab5 = new javax.swing.JLabel();
        lab4 = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        lab8 = new javax.swing.JLabel();
        lab9 = new javax.swing.JLabel();
        lab10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSalesToday = new javax.swing.JLabel();
        lblActual = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDifference = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        spn50 = new javax.swing.JSpinner();
        spn20 = new javax.swing.JSpinner();
        spn10 = new javax.swing.JSpinner();
        spn5 = new javax.swing.JSpinner();
        spn2 = new javax.swing.JSpinner();
        spn1 = new javax.swing.JSpinner();
        spn50cent = new javax.swing.JSpinner();
        spn20cent = new javax.swing.JSpinner();
        spn10cent = new javax.swing.JSpinner();
        spn5cent = new javax.swing.JSpinner();
        lab11 = new javax.swing.JLabel();
        spn2cent = new javax.swing.JSpinner();
        lab12 = new javax.swing.JLabel();
        spn1cent = new javax.swing.JSpinner();
        btnCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cash Up");

        jPanel1.setBackground(new java.awt.Color(50, 70, 111));
        jPanel1.setMaximumSize(new java.awt.Dimension(517, 642));
        jPanel1.setMinimumSize(new java.awt.Dimension(517, 642));

        lab7.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lab7.setForeground(new java.awt.Color(255, 255, 255));
        lab7.setText("€0.50");

        lab6.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lab6.setForeground(new java.awt.Color(255, 255, 255));
        lab6.setText("€1");

        lab5.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lab5.setForeground(new java.awt.Color(255, 255, 255));
        lab5.setText("€2");

        lab4.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lab4.setForeground(new java.awt.Color(255, 255, 255));
        lab4.setText("€5");

        lab3.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lab3.setForeground(new java.awt.Color(255, 255, 255));
        lab3.setText("€10");

        lab2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lab2.setForeground(new java.awt.Color(255, 255, 255));
        lab2.setText("€20");

        lab1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lab1.setForeground(new java.awt.Color(255, 255, 255));
        lab1.setText("€50");

        lab8.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lab8.setForeground(new java.awt.Color(255, 255, 255));
        lab8.setText("€0.20");

        lab9.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lab9.setForeground(new java.awt.Color(255, 255, 255));
        lab9.setText("€0.10");

        lab10.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lab10.setForeground(new java.awt.Color(255, 255, 255));
        lab10.setText("€0.05");

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Today's Sales:");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Actual Amount");

        lblSalesToday.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        lblSalesToday.setForeground(new java.awt.Color(255, 255, 255));

        lblActual.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        lblActual.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("€");

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("€");

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Difference");

        lblDifference.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        lblDifference.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("€");

        jButton1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left224.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        spn50.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        spn50.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spn50.setMinimumSize(new java.awt.Dimension(100, 30));
        spn50.setPreferredSize(new java.awt.Dimension(100, 30));

        spn20.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        spn20.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spn20.setMinimumSize(new java.awt.Dimension(100, 30));
        spn20.setPreferredSize(new java.awt.Dimension(100, 30));

        spn10.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        spn10.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spn10.setMinimumSize(new java.awt.Dimension(100, 30));
        spn10.setPreferredSize(new java.awt.Dimension(100, 30));

        spn5.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        spn5.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spn5.setMinimumSize(new java.awt.Dimension(100, 30));
        spn5.setPreferredSize(new java.awt.Dimension(100, 30));

        spn2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        spn2.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spn2.setMinimumSize(new java.awt.Dimension(100, 30));
        spn2.setPreferredSize(new java.awt.Dimension(100, 30));

        spn1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        spn1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spn1.setMinimumSize(new java.awt.Dimension(100, 30));
        spn1.setPreferredSize(new java.awt.Dimension(100, 30));

        spn50cent.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        spn50cent.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spn50cent.setMinimumSize(new java.awt.Dimension(100, 30));
        spn50cent.setPreferredSize(new java.awt.Dimension(100, 30));

        spn20cent.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        spn20cent.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spn20cent.setMinimumSize(new java.awt.Dimension(100, 30));
        spn20cent.setPreferredSize(new java.awt.Dimension(100, 30));

        spn10cent.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        spn10cent.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spn10cent.setMinimumSize(new java.awt.Dimension(100, 30));
        spn10cent.setPreferredSize(new java.awt.Dimension(100, 30));

        spn5cent.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        spn5cent.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spn5cent.setMinimumSize(new java.awt.Dimension(100, 30));
        spn5cent.setPreferredSize(new java.awt.Dimension(100, 30));

        lab11.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lab11.setForeground(new java.awt.Color(255, 255, 255));
        lab11.setText("€0.02");

        spn2cent.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        spn2cent.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spn2cent.setMinimumSize(new java.awt.Dimension(100, 30));
        spn2cent.setPreferredSize(new java.awt.Dimension(100, 30));

        lab12.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lab12.setForeground(new java.awt.Color(255, 255, 255));
        lab12.setText("€0.01");

        spn1cent.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        spn1cent.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        spn1cent.setMinimumSize(new java.awt.Dimension(100, 30));
        spn1cent.setPreferredSize(new java.awt.Dimension(100, 30));

        btnCalculate.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btnCalculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator66.png"))); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.setFocusCycleRoot(true);
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(97, 97, 97)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalesToday)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(35, 35, 35))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblActual, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDifference, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lab6)
                                        .addGap(66, 66, 66)
                                        .addComponent(spn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lab5)
                                        .addGap(66, 66, 66)
                                        .addComponent(spn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lab4)
                                        .addGap(66, 66, 66)
                                        .addComponent(spn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lab3)
                                        .addGap(59, 59, 59)
                                        .addComponent(spn10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(spn20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(spn50, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(102, 102, 102)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lab10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(spn5cent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lab9)
                                        .addGap(73, 73, 73)
                                        .addComponent(spn10cent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lab8)
                                        .addGap(73, 73, 73)
                                        .addComponent(spn20cent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lab7)
                                        .addGap(73, 73, 73)
                                        .addComponent(spn50cent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lab11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lab12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spn2cent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spn1cent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSalesToday)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spn50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab1))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab2)
                            .addComponent(spn20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab3)
                            .addComponent(spn10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab4)
                            .addComponent(spn5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab5)
                            .addComponent(spn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab6)
                            .addComponent(spn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab7)
                            .addComponent(spn50cent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab8)
                            .addComponent(spn20cent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spn10cent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab10)
                            .addComponent(spn5cent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spn2cent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spn1cent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lab12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(53, 53, 53)
                .addComponent(btnCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDifference, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)))
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new frmManager().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        //add values from spinners
        double fifty, twenty, ten, five, two, one, fiftycent, twentycent, tencent,fivecent, twocent,onecent,total;
        
        fifty = (double) spn50.getValue() * 50;
        twenty = (double) spn20.getValue()*20;
        ten = (double) spn10.getValue()*10;
        five = (double) spn5.getValue()*5;
        two = (double) spn2.getValue()*2;
        one= (double) spn1.getValue();
        fiftycent = (double) spn50cent.getValue()*.5;
        twentycent = (double) spn20cent.getValue()*.2;
        tencent = (double) spn10cent.getValue()*.1;
        fivecent= (double) spn5cent.getValue()*.05;
        twocent= (double) spn2cent.getValue()*.02;
        onecent= (double) spn1cent.getValue()*.01;

        total= fifty + twenty+ ten+ five+ two + one +
        fiftycent + twentycent + tencent + fivecent 
        + twocent + onecent;

        lblActual.setText(String.valueOf(total));
        
        double Difference =  total - salesToday;
        lblDifference.setText(String.valueOf(Difference));
        
    }//GEN-LAST:event_btnCalculateActionPerformed
    
    private void setUp(){
        //add all sales for the day
        
        
        try
        {
            createConnection();
            stmt = conn.createStatement();
            DateFormat df;
            df = new SimpleDateFormat("dd/MM/yyyy");
            Date d = new Date();
            String date = df.format(d);   
            ResultSet results = stmt.executeQuery("select PRICE from ORDERS where DATE = "+ "'"+date+"'");
            
            
            while(results.next())
            {
            tempString = results.getString(1);
            tempDouble = Double.valueOf(tempString);
            salesToday += tempDouble;
            
            }
            
            results.close();
            stmt.close();
            shutdown();
            lblSalesToday.setText(String.valueOf(salesToday));
        }
        catch (SQLException sqlExcept)
        {
           sqlExcept.printStackTrace();
        }
        
       
        ((JSpinner.DefaultEditor)spn50.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor)spn20.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor)spn10.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor)spn5.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor)spn2.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor)spn1.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor)spn50cent.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor)spn20cent.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor)spn10cent.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor)spn5cent.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor)spn2cent.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor)spn1cent.getEditor()).getTextField().setEditable(false);
    }
    
     public static void createConnection()
    {
        try
        {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver").newInstance();
            //Get a connection
            conn = DriverManager.getConnection(dbURL); 
        }
        catch (Exception except)
        {
            except.printStackTrace();
        }
    }
    
    //shuts down the connection to the database
    public static void shutdown()
    {
        try
        {
            if (stmt != null)
            {
                stmt.close();
            }
            if (conn != null)
            {
                DriverManager.getConnection(dbURL + ";shutdown=true");
                conn.close();
            }           
        }
        catch (SQLException sqlExcept)
        {
         //TODO Some code here
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCashUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCashUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCashUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCashUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCashUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab10;
    private javax.swing.JLabel lab11;
    private javax.swing.JLabel lab12;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel lab5;
    private javax.swing.JLabel lab6;
    private javax.swing.JLabel lab7;
    private javax.swing.JLabel lab8;
    private javax.swing.JLabel lab9;
    private javax.swing.JLabel lblActual;
    private javax.swing.JLabel lblDifference;
    private javax.swing.JLabel lblSalesToday;
    private javax.swing.JSpinner spn1;
    private javax.swing.JSpinner spn10;
    private javax.swing.JSpinner spn10cent;
    private javax.swing.JSpinner spn1cent;
    private javax.swing.JSpinner spn2;
    private javax.swing.JSpinner spn20;
    private javax.swing.JSpinner spn20cent;
    private javax.swing.JSpinner spn2cent;
    private javax.swing.JSpinner spn5;
    private javax.swing.JSpinner spn50;
    private javax.swing.JSpinner spn50cent;
    private javax.swing.JSpinner spn5cent;
    // End of variables declaration//GEN-END:variables
}
