package presentationTier;


import businessTier.cashButton;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 110310587
 */
public class frmSpecials extends javax.swing.JFrame {
    private static String dbURL = "jdbc:derby:DATABASE;create=true;user=test;password=test";
    private static Connection conn = null;
    private static Statement stmt = null;
    
   
    /**
     * Creates new form frmEditItems
     */
    //need to be changed from dialog
    
    public frmSpecials() {
        initComponents();
        //refresh the buttons
         //resize JTabbedForm tabs using labels 
        JLabel lab = new JLabel("Specials");
        lab.setPreferredSize(new Dimension(80, 80));
        tpnCashier.setTabComponentAt(0, lab);  // tab index, jLabel
        lab.setFont(new Font("Calibri", Font.PLAIN, 14));
        
        buttonRefresh(); 
   
    }
    public void buttonRefresh(){

        ResultSet itemSet = null;
        cashButton[] buttonArray = {btn101,btn102,btn103,btn104,btn105,btn106,btn107,
           btn108,btn109,btn110,btn111,btn112,btn113,btn114,btn115,btn116,btn117,btn118,btn119,btn120};
        try {
            createConnection();
            stmt = conn.createStatement();
  
            // get the number of rows from the result set
          
            itemSet = stmt.executeQuery("select * from ITEMS where ITEM_ID BETWEEN 100 AND 119");
            }
            catch (SQLException ex) {
            System.out.println("error");
        }
        
        try{
            int i =0;
            while(itemSet.next())
            {   
                buttonArray[i].setID(itemSet.getInt(1));
                buttonArray[i].setText(itemSet.getString(2));
                if("Special".equals(buttonArray[i].getText())){
                
                    buttonArray[i].setText(null);
                }
                buttonArray[i].setPrice(itemSet.getDouble(3));
                i++;
            }
        }
        catch(SQLException e){
            
        }
    
        //count the number of elements in array vs buttons. start at the length of the array. add
        //adapted from http://stackoverflow.com/questions/15125170/actionlistener-on-array-of-jbuttons
        //one action listener for all the buttons
        //demonstrates an overrided method.
        for (int i = 0; i< buttonArray.length; i++)
        {
            buttonArray[i].addActionListener(new ActionListener() 
            {
            @Override
            public void actionPerformed(ActionEvent e) 
                {
                cashButton button = (cashButton) e.getSource();
                dlgEdit.setVisible(true);
                lblCNameValue.setText(button.getText());
                lblCPriceValue.setText(String.valueOf(button.getPrice()));
                lblNumber.setText(String.valueOf(button.getID()));
                }
            });
        }
    }
      public static void createConnection()
    {
        try
        {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver").newInstance();
            //Get a connection
            conn = DriverManager.getConnection(dbURL); 
        }
        catch (Exception except)
        {
            except.printStackTrace();
        }
    }
    
    //shuts down the connection to the database
    public static void shutdown()
    {
        try
        {
            if (stmt != null)
            {
                stmt.close();
            }
            if (conn != null)
            {
                DriverManager.getConnection(dbURL + ";shutdown=true");
                conn.close();
            }           
        }
        catch (SQLException sqlExcept)
        {
         //TODO Some code here
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgEdit = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCNameValue = new javax.swing.JLabel();
        lblCPriceValue = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblNumber = new javax.swing.JLabel();
        btnDisable = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tpnCashier = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btn101 = new businessTier.cashButton();
        btn102 = new businessTier.cashButton();
        btn103 = new businessTier.cashButton();
        btn104 = new businessTier.cashButton();
        btn105 = new businessTier.cashButton();
        btn106 = new businessTier.cashButton();
        btn107 = new businessTier.cashButton();
        btn108 = new businessTier.cashButton();
        btn109 = new businessTier.cashButton();
        btn110 = new businessTier.cashButton();
        btn111 = new businessTier.cashButton();
        btn112 = new businessTier.cashButton();
        btn113 = new businessTier.cashButton();
        btn114 = new businessTier.cashButton();
        btn115 = new businessTier.cashButton();
        btn116 = new businessTier.cashButton();
        btn117 = new businessTier.cashButton();
        btn118 = new businessTier.cashButton();
        btn119 = new businessTier.cashButton();
        btn120 = new businessTier.cashButton();

        dlgEdit.setTitle("Set Specials");
        dlgEdit.setMinimumSize(new java.awt.Dimension(400, 400));
        dlgEdit.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                dlgEditWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(50, 70, 111));
        jPanel2.setMinimumSize(new java.awt.Dimension(360, 360));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Current Name:");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current Price:");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Name:");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Price:");

        lblCNameValue.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lblCNameValue.setForeground(new java.awt.Color(255, 255, 255));
        lblCNameValue.setText("jLabel5");

        lblCPriceValue.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lblCPriceValue.setForeground(new java.awt.Color(255, 255, 255));
        lblCPriceValue.setText("jLabel6");

        txtName.setBackground(new java.awt.Color(204, 204, 214));
        txtName.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        btnOk.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btnOk.setText("Save Changes");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblNumber.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lblNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblNumber.setText("jLabel6");

        btnDisable.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btnDisable.setText("Disable Button");
        btnDisable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisableActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Item No:");

        txtPrice.setBackground(new java.awt.Color(204, 204, 214));
        txtPrice.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(btnCancel)
                    .addComponent(jLabel6))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisable, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addComponent(lblCPriceValue)
                    .addComponent(lblCNameValue)
                    .addComponent(lblNumber)
                    .addComponent(txtPrice))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCNameValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCPriceValue))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnDisable)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgEditLayout = new javax.swing.GroupLayout(dlgEdit.getContentPane());
        dlgEdit.getContentPane().setLayout(dlgEditLayout);
        dlgEditLayout.setHorizontalGroup(
            dlgEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgEditLayout.setVerticalGroup(
            dlgEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(0, 805));

        jPanel1.setBackground(new java.awt.Color(50, 70, 111));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left224.png"))); // NOI18N
        jButton2.setText("Back To Manager");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(50, 70, 111));

        tpnCashier.setBackground(new java.awt.Color(204, 204, 214));
        tpnCashier.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tpnCashier.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tpnCashier.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        tpnCashier.setMinimumSize(new java.awt.Dimension(610, 810));
        tpnCashier.setPreferredSize(new java.awt.Dimension(610, 800));

        jPanel3.setBackground(new java.awt.Color(50, 70, 111));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(537, 700));

        btn101.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn101.setMaximumSize(new java.awt.Dimension(120, 120));
        btn101.setMinimumSize(new java.awt.Dimension(120, 120));
        btn101.setPreferredSize(new java.awt.Dimension(120, 120));

        btn102.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn102.setMaximumSize(new java.awt.Dimension(120, 120));
        btn102.setMinimumSize(new java.awt.Dimension(120, 120));
        btn102.setPreferredSize(new java.awt.Dimension(120, 120));

        btn103.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn103.setMaximumSize(new java.awt.Dimension(120, 120));
        btn103.setMinimumSize(new java.awt.Dimension(120, 120));
        btn103.setPreferredSize(new java.awt.Dimension(120, 120));

        btn104.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn104.setMaximumSize(new java.awt.Dimension(120, 120));
        btn104.setMinimumSize(new java.awt.Dimension(120, 120));
        btn104.setPreferredSize(new java.awt.Dimension(120, 120));

        btn105.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn105.setMaximumSize(new java.awt.Dimension(120, 120));
        btn105.setMinimumSize(new java.awt.Dimension(120, 120));
        btn105.setPreferredSize(new java.awt.Dimension(120, 120));

        btn106.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn106.setMaximumSize(new java.awt.Dimension(120, 120));
        btn106.setMinimumSize(new java.awt.Dimension(120, 120));
        btn106.setPreferredSize(new java.awt.Dimension(120, 120));

        btn107.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn107.setMaximumSize(new java.awt.Dimension(120, 120));
        btn107.setMinimumSize(new java.awt.Dimension(120, 120));
        btn107.setPreferredSize(new java.awt.Dimension(120, 120));

        btn108.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn108.setMaximumSize(new java.awt.Dimension(120, 120));
        btn108.setMinimumSize(new java.awt.Dimension(120, 120));
        btn108.setPreferredSize(new java.awt.Dimension(120, 120));

        btn109.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn109.setMaximumSize(new java.awt.Dimension(120, 120));
        btn109.setMinimumSize(new java.awt.Dimension(120, 120));
        btn109.setPreferredSize(new java.awt.Dimension(120, 120));

        btn110.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn110.setMaximumSize(new java.awt.Dimension(120, 120));
        btn110.setMinimumSize(new java.awt.Dimension(120, 120));
        btn110.setPreferredSize(new java.awt.Dimension(120, 120));

        btn111.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn111.setMaximumSize(new java.awt.Dimension(120, 120));
        btn111.setMinimumSize(new java.awt.Dimension(120, 120));
        btn111.setPreferredSize(new java.awt.Dimension(120, 120));

        btn112.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn112.setMaximumSize(new java.awt.Dimension(120, 120));
        btn112.setMinimumSize(new java.awt.Dimension(120, 120));
        btn112.setPreferredSize(new java.awt.Dimension(120, 120));

        btn113.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn113.setMaximumSize(new java.awt.Dimension(120, 120));
        btn113.setMinimumSize(new java.awt.Dimension(120, 120));
        btn113.setPreferredSize(new java.awt.Dimension(120, 120));

        btn114.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn114.setMaximumSize(new java.awt.Dimension(120, 120));
        btn114.setMinimumSize(new java.awt.Dimension(120, 120));
        btn114.setPreferredSize(new java.awt.Dimension(120, 120));

        btn115.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn115.setMaximumSize(new java.awt.Dimension(120, 120));
        btn115.setMinimumSize(new java.awt.Dimension(120, 120));
        btn115.setPreferredSize(new java.awt.Dimension(120, 120));

        btn116.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn116.setMaximumSize(new java.awt.Dimension(120, 120));
        btn116.setMinimumSize(new java.awt.Dimension(120, 120));
        btn116.setPreferredSize(new java.awt.Dimension(120, 120));

        btn117.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn117.setMaximumSize(new java.awt.Dimension(120, 120));
        btn117.setMinimumSize(new java.awt.Dimension(120, 120));
        btn117.setPreferredSize(new java.awt.Dimension(120, 120));

        btn118.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn118.setMaximumSize(new java.awt.Dimension(120, 120));
        btn118.setMinimumSize(new java.awt.Dimension(120, 120));
        btn118.setPreferredSize(new java.awt.Dimension(120, 120));

        btn119.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn119.setMaximumSize(new java.awt.Dimension(120, 120));
        btn119.setMinimumSize(new java.awt.Dimension(120, 120));
        btn119.setPreferredSize(new java.awt.Dimension(120, 120));

        btn120.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btn120.setMaximumSize(new java.awt.Dimension(120, 120));
        btn120.setMinimumSize(new java.awt.Dimension(120, 120));
        btn120.setPreferredSize(new java.awt.Dimension(120, 120));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn117, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn116, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn109, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn108, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn101, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn107, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn115, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn118, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn114, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn119, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn112, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn113, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn120, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn102, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn101, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn103, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn104, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn107, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn109, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn112, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn116, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn115, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn114, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn113, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn117, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn118, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn119, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn120, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tpnCashier.addTab("Specials", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tpnCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tpnCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton2)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new frmManager().setVisible(true);
        //delete the form - not taking up memory!
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        //TODO save and refresh buttons
        //make changes to string[i], name[i]
        int i = Integer.valueOf(lblNumber.getText());
        System.out.println(String.valueOf(i));
        String tempName = txtName.getText();
        String tempPrice = txtPrice.getText();
        //write buttons to database
        try 
        {
        Double.parseDouble(tempPrice);
        
            try
            {
            createConnection();
            stmt = conn.createStatement();
            //insert code from http://www.tutorialspoint.com/jdbc/jdbc-insert-records.htm
            String sql = "UPDATE ITEMS set NAME ='" +tempName+ "', PRICE = '" + tempPrice + "', SPECIAL = true WHERE ITEM_ID ="+ i ;

            stmt.executeUpdate(sql);
            
            }
            catch(SQLException e)
            {
              System.out.println(e);
            }

            buttonRefresh();
            dlgEdit.dispose();
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Please enter numeric values only.", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dlgEdit.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void dlgEditWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgEditWindowActivated
       
    }//GEN-LAST:event_dlgEditWindowActivated
  
    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        char c = evt.getKeyChar();
        if(c == '\'') {
        txtName.setText("");
        txtName.grabFocus();
        java.awt.Toolkit.getDefaultToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txtNameKeyTyped
    ////TODO - NOT WORKING stop entry of ' to avoid sql errors  http://www.coderanch.com/t/334759/GUI/java/Disallow-chars-JTextField
    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        
    }//GEN-LAST:event_txtNameKeyPressed

    private void btnDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisableActionPerformed
        int i = Integer.valueOf(lblNumber.getText());
        try
        {
        createConnection();
        stmt = conn.createStatement();
        //insert code from http://www.tutorialspoint.com/jdbc/jdbc-insert-records.htm
        String sql = "UPDATE ITEMS set NAME ='Special', PRICE = '0', SPECIAL = true WHERE ITEM_ID ="+ i ;
        stmt.executeUpdate(sql);
        System.out.println("UPDATE successful");
        }
        catch(SQLException e)
        {
          System.out.println(e);
        }
        
        buttonRefresh();
        dlgEdit.dispose();
    }//GEN-LAST:event_btnDisableActionPerformed

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        char c = evt.getKeyChar();
        if(c == '\'') {
        txtName.setText("");
        txtName.grabFocus();
        java.awt.Toolkit.getDefaultToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txtPriceKeyTyped

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSpecials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSpecials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSpecials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSpecials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSpecials().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private businessTier.cashButton btn101;
    private businessTier.cashButton btn102;
    private businessTier.cashButton btn103;
    private businessTier.cashButton btn104;
    private businessTier.cashButton btn105;
    private businessTier.cashButton btn106;
    private businessTier.cashButton btn107;
    private businessTier.cashButton btn108;
    private businessTier.cashButton btn109;
    private businessTier.cashButton btn110;
    private businessTier.cashButton btn111;
    private businessTier.cashButton btn112;
    private businessTier.cashButton btn113;
    private businessTier.cashButton btn114;
    private businessTier.cashButton btn115;
    private businessTier.cashButton btn116;
    private businessTier.cashButton btn117;
    private businessTier.cashButton btn118;
    private businessTier.cashButton btn119;
    private businessTier.cashButton btn120;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDisable;
    private javax.swing.JButton btnOk;
    private javax.swing.JDialog dlgEdit;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCNameValue;
    private javax.swing.JLabel lblCPriceValue;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JTabbedPane tpnCashier;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}

