/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentationTier;

import businessTier.cashButton;
import businessTier.cashier;
import businessTier.tableButton;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author 110310587
 */
public class frmTables extends javax.swing.JFrame {
    private int EMP_ID;
    private String FNAME;
    private String SNAME;
    private int TABLE_ID;
   private cashier currentCashier;
    /**
     * Creates new form frmTables
     */
    public frmTables() {
        initComponents();
        setUp();
    }
    
    public frmTables(cashier iCurrentCashier){
        initComponents();
        currentCashier = iCurrentCashier;
        setUp();
    }
    
    private void setUp(){
 
        tableButton[] buttonArray ={btn1,btn2,btn3,btn4,btn5,btn6,btn7,btn8,btn9,btn10,btn11,btn12,btn13,btn14,btn15,btn16,btn17,btn18,btn19,btn20,btn21};
         for (int i = 0; i< buttonArray.length; i++)
        {
            buttonArray[i].setTableNo(i+1);
            buttonArray[i].addActionListener(new ActionListener() 
            {
            @Override
            public void actionPerformed(ActionEvent e) 
                {
                    tableButton button = (tableButton) e.getSource();
                    TABLE_ID = button.getTableNo();
                    
                    new frmCashier(currentCashier,TABLE_ID).setVisible(true);
                    //delete the form - not taking up memory!
                    disposeMe();
                }
            });
        }
    }
    private void disposeMe(){
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new businessTier.tableButton();
        btn2 = new businessTier.tableButton();
        btn3 = new businessTier.tableButton();
        btn4 = new businessTier.tableButton();
        btn6 = new businessTier.tableButton();
        btn16 = new businessTier.tableButton();
        btn17 = new businessTier.tableButton();
        btn18 = new businessTier.tableButton();
        btn19 = new businessTier.tableButton();
        btn20 = new businessTier.tableButton();
        btn21 = new businessTier.tableButton();
        btn14 = new businessTier.tableButton();
        btn8 = new businessTier.tableButton();
        btn9 = new businessTier.tableButton();
        btn10 = new businessTier.tableButton();
        btn11 = new businessTier.tableButton();
        btn12 = new businessTier.tableButton();
        btn13 = new businessTier.tableButton();
        btn5 = new businessTier.tableButton();
        btn15 = new businessTier.tableButton();
        btn7 = new businessTier.tableButton();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Table");
        setMinimumSize(new java.awt.Dimension(1180, 640));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(50, 70, 111));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 460));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 460));
        jPanel1.setLayout(null);

        btn1.setText("1");
        btn1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn1);
        btn1.setBounds(216, 84, 72, 50);

        btn2.setText("2");
        btn2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn2);
        btn2.setBounds(347, 84, 72, 50);

        btn3.setText("3");
        btn3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn3);
        btn3.setBounds(511, 84, 72, 50);

        btn4.setText("4");
        btn4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn4);
        btn4.setBounds(675, 84, 72, 50);

        btn6.setText("6");
        btn6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn6);
        btn6.setBounds(223, 198, 48, 48);

        btn16.setText("16");
        btn16.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn16);
        btn16.setBounds(84, 422, 72, 50);

        btn17.setText("17");
        btn17.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn17);
        btn17.setBounds(216, 422, 72, 50);

        btn18.setText("18");
        btn18.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn18);
        btn18.setBounds(347, 422, 72, 50);

        btn19.setText("19");
        btn19.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn19);
        btn19.setBounds(511, 422, 72, 50);

        btn20.setText("20");
        btn20.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn20);
        btn20.setBounds(671, 422, 72, 50);

        btn21.setText("21");
        btn21.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn21);
        btn21.setBounds(810, 422, 72, 50);

        btn14.setText("14");
        btn14.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn14);
        btn14.setBounds(686, 309, 48, 48);

        btn8.setText("8");
        btn8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);
        btn8.setBounds(524, 197, 48, 48);

        btn9.setText("9");
        btn9.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn9);
        btn9.setBounds(687, 197, 49, 48);

        btn10.setText("10");
        btn10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn10);
        btn10.setBounds(83, 310, 48, 48);

        btn11.setText("11");
        btn11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn11);
        btn11.setBounds(226, 310, 49, 48);

        btn12.setText("12");
        btn12.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn12);
        btn12.setBounds(357, 309, 48, 48);

        btn13.setText("13");
        btn13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        jPanel1.add(btn13);
        btn13.setBounds(524, 309, 48, 48);

        btn5.setText("5");
        btn5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn5);
        btn5.setBounds(83, 198, 48, 48);

        btn15.setText("15");
        btn15.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn15);
        btn15.setBounds(822, 309, 49, 48);

        btn7.setText("7");
        btn7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(btn7);
        btn7.setBounds(355, 197, 49, 49);

        btnLogout.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login18.png"))); // NOI18N
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(30, 540, 160, 40);

        jLabel2.setBackground(new java.awt.Color(204, 204, 214));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Floor_Plan (2).PNG"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(25, 25, 1120, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1300, 660);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn13ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new frmWelcome().setVisible(true);
        //delete the current employee
        
        //delete the form - not taking up memory!
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private businessTier.tableButton btn1;
    private businessTier.tableButton btn10;
    private businessTier.tableButton btn11;
    private businessTier.tableButton btn12;
    private businessTier.tableButton btn13;
    private businessTier.tableButton btn14;
    private businessTier.tableButton btn15;
    private businessTier.tableButton btn16;
    private businessTier.tableButton btn17;
    private businessTier.tableButton btn18;
    private businessTier.tableButton btn19;
    private businessTier.tableButton btn2;
    private businessTier.tableButton btn20;
    private businessTier.tableButton btn21;
    private businessTier.tableButton btn3;
    private businessTier.tableButton btn4;
    private businessTier.tableButton btn5;
    private businessTier.tableButton btn6;
    private businessTier.tableButton btn7;
    private businessTier.tableButton btn8;
    private businessTier.tableButton btn9;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
