/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentationTier;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author 110310587
 */
//Welcome screen - allows user to sign in to management and cashier features
public class frmWelcome extends javax.swing.JFrame {
     //derby variables
     private static String dbURL = "jdbc:derby:DATABASE;create=true;user=test;password=test";
     private static Connection conn = null;
     private static Statement stmt = null;
    /**
     * Creates new form frmWelcome
     */
    public frmWelcome() {
        initComponents();
        //reset signed in to false on all employees in case session was terminated accidentally
        
        try
        {
        createConnection();
        stmt = conn.createStatement();
        String sql ="update EMPLOYEES set SIGNED_IN = false";
        stmt.executeUpdate(sql);
        stmt.close();
        }
        
         
        catch(SQLException e){
           //JOptionPane.showMessageDialog(null, "Data Error. Please contact system maintenance." + "/n" + "Error message:" + e.toString(), "Data Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCashierLogin = new javax.swing.JButton();
        btnManagerLogin = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Captain Americas!");

        jPanel1.setBackground(new java.awt.Color(14, 30, 71));
        jPanel1.setMinimumSize(new java.awt.Dimension(846, 481));
        jPanel1.setLayout(null);

        btnCashierLogin.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btnCashierLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login17.png"))); // NOI18N
        btnCashierLogin.setText("Cashier Log In");
        btnCashierLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnCashierLogin);
        btnCashierLogin.setBounds(110, 270, 200, 70);

        btnManagerLogin.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btnManagerLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login17.png"))); // NOI18N
        btnManagerLogin.setText("Manager Log In");
        btnManagerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnManagerLogin);
        btnManagerLogin.setBounds(530, 270, 200, 70);

        btnQuit.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/power103.png"))); // NOI18N
        btnQuit.setText("Exit Program");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuit);
        btnQuit.setBounds(350, 400, 172, 47);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/corkca.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, -50, 430, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        //close the program - parameter of 0 indicates that the program was terminated normally and not due to an error.
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed
    //logs in as manager
    private void btnManagerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerLoginActionPerformed
        new frmLogin(true).setVisible(true);
        //delete the form - not taking up memory!
        this.dispose();
    }//GEN-LAST:event_btnManagerLoginActionPerformed
    //logs n as cashier
    private void btnCashierLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierLoginActionPerformed
        new frmLogin().setVisible(true);
        //delete the form - not taking up memory!
        this.dispose();
    }//GEN-LAST:event_btnCashierLoginActionPerformed
    
    
    /*exit
     //close the program - parameter of 0 indicates that the program was terminated normally and not due to an error.
        System.exit(0);
    //manager login
    new frmLogin(true).setVisible(true);
        //delete the form - not taking up memory!
        this.dispose();
    */
     private static void createConnection()
    {
        try
        {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver").newInstance();
            //Get a connection
            conn = DriverManager.getConnection(dbURL); 
        }
        catch (Exception except)
        {
            except.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmWelcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCashierLogin;
    private javax.swing.JButton btnManagerLogin;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
